### PR TITLE
FIX: display and synchronization

### LINKED ISSUE #33: Send a signal to one of the digital channels at the beginning of the psychopy task

### LINKED ISSUE #35: Change the background color during tasks

### LINKED ISSUE #36: Remove fixation point in the middle of DWI

### LINKED ISSUE #38: Library hcphsignals cannot be imported from psychopy code block

### LINKED ISSUE #39: The background color of QCT stays the same despite changes in the psychopy builder.

### PR DESCRIPTION
**Pull request by esavary**
- Replace the unique fixation point in DWI with 30s fixation at the beginning and the end of the task. closes #36 
- Change the background color of the task to black. closes #35 
- Send a signal to the last channel at the beginning of the tasks. closes #33
-   closes #39 
-  closes #38

### CODE REVIEW

**Comment by esavary** [comment]
The code was changed, but the background color during QCT is still grey. I will fix it in a next PR.

**Comment by esavary** [comment]
@oesteban, Can we merge this PR before the session today? (It contains the validation task too).

**Comment by esavary** [comment]
closes #39

**Review by oesteban — APPROVED** [review]
I'm going to hit approve because currently tasks are crashing with the `/home/common` directory access problem (which is expected, should use `pathlib.Path.home()` for that...)

It's really difficult to code review pyexp files and even harder if the PR is an omnibus overhaul... Let's get this merge and try to make changes more targeted from now on.

**Pull request merged**
